apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-message-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-message-pod
  template:
    metadata:
      labels:
        app: kube-message-pod
    spec:
      containers:
        - name: kube-message-container
          image: joydipdocker/message-app:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
