apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-container
          image: joydipdocker/auth-api-image:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
