version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - "3000:3000"
  users:
    build: ./users-api
    ports:
      - "3001:3001"
  tasks:
    build: ./tasks-api
    ports:
      - "3002:3002"
    environment:
      TASKS_FOLDER: tasks
