apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-pod
  template:
    metadata:
      labels:
        app: story-pod
    spec:
      containers:
        - name: story-container
          image: joydipdocker/story-image:v2
          volumeMounts:
            - name: story-volume
              mountPath: /app/story
      volumes:
        - name: story-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate
