apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  # 1. claim by name
  volumeName: host-pv
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
